language: c
sudo: required
services:
   - docker

env:
   matrix:
      - ITEST_TARGET=itest_lucid
      - ITEST_TARGET=itest_precise
      - ITEST_TARGET=itest_trusty
      - ITEST_TARGET=itest_wheezy
      - ITEST_TARGET=itest_jessie
      - ITEST_TARGET=itest_stretch

script:
   - make "$ITEST_TARGET"
