language: c
services:
    - docker

addons:
    artifacts:
        target_paths:
            - /dumb-init/${TRAVIS_BUILD_NUMBER}/${ITEST_TARGET}
        paths:
            - $(find dist -type f | tr "\n" ':')

env:
    matrix:
        - ITEST_TARGET=itest_trusty
        - ITEST_TARGET=itest_xenial
        - ITEST_TARGET=itest_bionic
        - ITEST_TARGET=itest_jessie
        - ITEST_TARGET=itest_stretch
        - ITEST_TARGET=itest_tox

script:
   - make "$ITEST_TARGET"

after_script:
   - if [ -n "${ARTIFACTS_SECRET:-}" ]; then
         echo 'Build artifacts are available at:';
         find dist -type f | xargs --replace echo "* https://yelp-travis-artifacts.s3.amazonaws.com/dumb-init/${TRAVIS_BUILD_NUMBER}/${ITEST_TARGET}/{}";
     fi
